services:
  redis:
    extends:
      file: docker-compose.yaml
      service: redis
  async_api:
    extends:
      file: docker-compose.yaml
      service: async_api
    volumes:
    - ./src:/opt/app/src
    ports:
    - 8000:8000
    environment:
      DEV: 'true'

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge

volumes:
  redis-data: