version: '3'
services:
  redis:
    image: redis:6.0.9
    ports:
      - 6379:6379
    volumes:
      - redis-data:/opt/app/redis/data
    networks:
      - movies-api-network
    restart: unless-stopped

  async_api:
    container_name: async_api
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      PROJECT_NAME: "Movies API"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTIC_HOST: 127.0.0.1
      ELASTIC_PORT: 9200
    networks:
      - movies-api-network
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:

networks:
  movies-api-network:
    name: movies-api-network
    driver: bridge
