version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.10.1
    environment:
      discovery.type: "single-node"
    ports:
      - 9200:9200
    volumes:
      - elasticdb:/opt/app/elasticsearch/data
    restart:
      on-failure

  redis:
    image: redis:6.0.9
    ports:
      - 6379:6379
    volumes:
      - redisdata:/opt/app/redis/data
    restart: on-failure

  async_api:
    container_name: async_api
    build:
      context: .
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - redis
    restart: on-failure

volumes:
  elasticdb:
  redisdata:
